version: '3.8'

services:
  app:
    build: .
    image: darkatlas-app
    container_name: darkatlas-app
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: darkatlas-db
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - darkatlas_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U darkatlas"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-db:
    image: postgres:16
    container_name: darkatlas-test-db
    ports:
      - "5433:5432"
    env_file:
      - .env.db
    environment:
      - POSTGRES_DB=darkatlas_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U darkatlas"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  darkatlas_prod_data: