"""initial schema

Revision ID: 7910d702d270
Revises: 
Create Date: 2026-06-23 12:43:18.058259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '7910d702d270'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('domain', 'subdomain', 'ip_address', 'service', 'certificate', 'technology', name='assettype'), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', 'archived', name='assetstatus'), nullable=False),
    sa.Column('source', sa.Enum('import_', 'scan', 'manual', name='assetsource'), nullable=False),
    sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_tags'), 'assets', ['tags'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole'), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('asset_relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('from_asset_id', sa.Uuid(), nullable=False),
    sa.Column('to_asset_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('parent_of', 'resolves_to', 'runs_on', 'covers', 'detected_on', name='relationshiptype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_asset_id', 'to_asset_id', 'relationship_type', name='uq_relationship')
    )
    op.create_index(op.f('ix_asset_relationships_from_asset_id'), 'asset_relationships', ['from_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_to_asset_id'), 'asset_relationships', ['to_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_relationships_to_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_from_asset_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_assets_tags'), table_name='assets')
    op.drop_table('assets')
    op.drop_table('orgs')
    # ### end Alembic commands ###
